name: Build and push React build to deploy branch

on:
  push:
    branches:
      - main   # change if you use a different primary branch

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: CI=false npm run build  # <-- added CI=false

      - name: Push build/ to deploy branch
        env:
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          # Make a temporary clone (clean) and push build/ contents into 'deploy' branch
          TMP_DIR=deploy_tmp
          rm -rf $TMP_DIR
          mkdir $TMP_DIR
          cd $TMP_DIR
          git init
          git remote add origin https://github.com/${REPO}.git

          # If deploy branch exists, fetch it so push will update it
          git fetch --depth=1 origin deploy || true
          git checkout --orphan deploy || git checkout -b deploy

          # Clean and copy build output
          git rm -rf . || true
          cp -r ../build/. .

          # Commit and push (use the built-in token)
          git add -A
          git commit -m "Deploy: $GITHUB_SHA" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git deploy --force
